# 生产环境配置示例

server:
  host: "0.0.0.0"
  port: 8000
  workers: 8  # 根据 CPU 核心数调整
  log_level: "warning"

plugins:
  auth: "default_auth"
  model_route: "default_router"
  stats: ["log"]

auth:
  default_auth:
    api_keys:
      - "sk-prod-key-1"
      - "sk-prod-key-2"

models:
  gpt-3.5-turbo:
    api_base: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"  # 从环境变量读取
    timeout: 60
  
  gpt-4:
    api_base: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    timeout: 120
  
  gpt-4-turbo:
    api_base: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    timeout: 120

rate_limit:
  enabled: true
  requests_per_minute: 100
